name = "ITensorGLMakie"
uuid = "3f718f31-6db8-4f43-a433-67cb5c73363e"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.1.1"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ITensorMakie = "72ca75eb-df6f-4d6b-80c5-d5eab17be3f9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
GLMakie = "0.7, 0.8"
ITensorMakie = "0.1.2"
Reexport = "1.2.2"
julia = "1.6"
